[package]
name = "republic"
version = "0.1.0"
authors = ["Chojan Shang <psiace@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^2.0.0"
actix-rt = "^1.0.0"
chrono = "~0.4.10"
env_logger = "~0.7.1"
log = "~0.4.8"
